import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Pages/Header";
import { MyProvider } from "./Context/Mycontext";
import Footer from "./Pages/Footer";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Link To Qrcode",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyProvider>
        <div className='sticky top-0 bg-white  shadow-md'>
        <Header />
      </div>
        {children}
        <Footer />
        <ToastContainer />
        </MyProvider>
      </body>
    </html>
  );
}
